[Bus1]
BusNumber = "1"
EvtPluginINIFilePath = "EventFromCSVPlugin/EventFromCSVPlugin.ini"
EvtParams.<size(s)> = "1 1"
EvtParams 0 = "C:\Projects\PARTF\trunk\Framework\Events\EventPlugins\Mathscript\CSVPlugin\CSV files\DynamicEvent_case3_1pmus.csv"
EvtConfig.UTC Time 0 = "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00"
EvtConfig.Nominal Frequency = "60"
EvtConfig.Reporting Rate = "60"
EvtConfig.Fsamp = "960"
EvtConfig.PosSeq = "FALSE"
Start Time = "0"
End Time = "10"
PmuImpairPluginINIFilePath = "NoPmuImpairPlugin/NoPmuImpairPlugin.ini"
PmuImpairParams .<size(s)> = "0 0"
PmuImpairConfig.FilterType = "Blackman"
PmuImpairConfig.bPosSeq = "FALSE"
NetImpPluginINIFilePath = "NetworkPluginNone/NetworkPluginNone.ini"
NetImpParams.<size(s)> = "0 0"
FlagImpPluginINIFilePath = "NoFlagImpairPlugin/NoFlagImpairPlugin.ini"
FlagImpParams.<size(s)> = "0 0"

[AppData]
AppData.AppPluginIniFilePath = "ModelValidationPlugin/ModelValidationPlugin.ini"
AppData.Config = ""

[OutToFileConfig]
OutToFileConfig.OutputToFilePluginINIFilePath = "OutputToFileBasePlugin/OutputToFileBasePlugin.ini"
OutToFileConfig.Output File Path = "Output"
OutToFileConfig.clConfigOptions.TIME_BASE = "\00\00\00\00\00\0FB@"
OutToFileConfig.clConfigOptions.STN = "Bus_1"
OutToFileConfig.clConfigOptions.IDCODE = "0"
OutToFileConfig.clConfigOptions.rdoPolRect = "Rectangular"
OutToFileConfig.clConfigOptions.rdoFloatInt = "Float"
OutToFileConfig.clConfigOptions.PHUNIT = "\00\00\00\00\00\0FB@"
OutToFileConfig.clConfigOptions.rdoFreqDfreq = "Float"
OutToFileConfig.clConfigOptions.CHNAM.<size(s)> = "8"
OutToFileConfig.clConfigOptions.CHNAM 0 = "VA"
OutToFileConfig.clConfigOptions.CHNAM 1 = "VB"
OutToFileConfig.clConfigOptions.CHNAM 2 = "VC"
OutToFileConfig.clConfigOptions.CHNAM 3 = "V+"
OutToFileConfig.clConfigOptions.CHNAM 4 = "IA"
OutToFileConfig.clConfigOptions.CHNAM 5 = "IB"
OutToFileConfig.clConfigOptions.CHNAM 6 = "IC"
OutToFileConfig.clConfigOptions.CHNAM 7 = "I+"
OutToFileConfig.clConfigOptions.chkCfg2Prefix = "TRUE"
