[Bus1]
BusNumber = "1"
EvtPluginINIFilePath = "EventFromCSVPlugin/EventFromCSVPlugin.ini"
EvtParams.<size(s)> = "1 1"
EvtParams 0 = "C:\Projects\PARTF\trunk\Framework\Events\EventPlugins\Mathscript\CSVPlugin\CSV files\DynamicEvent_case13_4pmus.csv"
EvtConfig.UTC Time 0 = "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00"
EvtConfig.Nominal Frequency = "60"
EvtConfig.Reporting Rate = "60"
EvtConfig.Fsamp = "960"
EvtConfig.PosSeq = "FALSE"
Start Time = "0"
End Time = "5"
PmuImpairPluginINIFilePath = "NoPmuImpairPlugin/NoPmuImpairPlugin.ini"
PmuImpairParams .<size(s)> = "0 0"
PmuImpairConfig.FilterType = "Blackman"
PmuImpairConfig.bPosSeq = "FALSE"
NetImpPluginINIFilePath = "NetworkPluginNone/NetworkPluginNone.ini"
NetImpParams.<size(s)> = "0 0"
FlagImpPluginINIFilePath = "NoFlagImpairPlugin/NoFlagImpairPlugin.ini"
FlagImpParams.<size(s)> = "0 0"

[Bus2]
BusNumber = "2"
EvtPluginINIFilePath = "EventFromCSVPlugin/EventFromCSVPlugin.ini"
EvtParams.<size(s)> = "1 1"
EvtParams 0 = "C:\Projects\PARTF\trunk\Framework\Events\EventPlugins\Mathscript\CSVPlugin\CSV files\DynamicEvent_case13_4pmus.csv"
EvtConfig.UTC Time 0 = "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00"
EvtConfig.Nominal Frequency = "60"
EvtConfig.Reporting Rate = "60"
EvtConfig.Fsamp = "960"
EvtConfig.PosSeq = "FALSE"
Start Time = "0"
End Time = "5"
PmuImpairPluginINIFilePath = "NoPmuImpairPlugin/NoPmuImpairPlugin.ini"
PmuImpairParams .<size(s)> = "0 0"
PmuImpairConfig.FilterType = "Blackman"
PmuImpairConfig.bPosSeq = "FALSE"
NetImpPluginINIFilePath = "NetworkPluginNone/NetworkPluginNone.ini"
NetImpParams.<size(s)> = "0 0"
FlagImpPluginINIFilePath = "NoFlagImpairPlugin/NoFlagImpairPlugin.ini"
FlagImpParams.<size(s)> = "0 0"

[Bus3]
BusNumber = "3"
EvtPluginINIFilePath = "EventFromCSVPlugin/EventFromCSVPlugin.ini"
EvtParams.<size(s)> = "1 1"
EvtParams 0 = "C:\Projects\PARTF\trunk\Framework\Events\EventPlugins\Mathscript\CSVPlugin\CSV files\DynamicEvent_case13_4pmus.csv"
EvtConfig.UTC Time 0 = "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00"
EvtConfig.Nominal Frequency = "60"
EvtConfig.Reporting Rate = "60"
EvtConfig.Fsamp = "960"
EvtConfig.PosSeq = "FALSE"
Start Time = "0"
End Time = "5"
PmuImpairPluginINIFilePath = "NoPmuImpairPlugin/NoPmuImpairPlugin.ini"
PmuImpairParams .<size(s)> = "0 0"
PmuImpairConfig.FilterType = "Blackman"
PmuImpairConfig.bPosSeq = "FALSE"
NetImpPluginINIFilePath = "NetworkPluginNone/NetworkPluginNone.ini"
NetImpParams.<size(s)> = "0 0"
FlagImpPluginINIFilePath = "NoFlagImpairPlugin/NoFlagImpairPlugin.ini"
FlagImpParams.<size(s)> = "0 0"

[Bus4]
BusNumber = "4"
EvtPluginINIFilePath = "EventFromCSVPlugin/EventFromCSVPlugin.ini"
EvtParams.<size(s)> = "1 1"
EvtParams 0 = "C:\Projects\PARTF\trunk\Framework\Events\EventPlugins\Mathscript\CSVPlugin\CSV files\DynamicEvent_case13_4pmus.csv"
EvtConfig.UTC Time 0 = "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00"
EvtConfig.Nominal Frequency = "60"
EvtConfig.Reporting Rate = "60"
EvtConfig.Fsamp = "960"
EvtConfig.PosSeq = "FALSE"
Start Time = "0"
End Time = "5"
PmuImpairPluginINIFilePath = "NoPmuImpairPlugin/NoPmuImpairPlugin.ini"
PmuImpairParams .<size(s)> = "0 0"
PmuImpairConfig.FilterType = "Blackman"
PmuImpairConfig.bPosSeq = "FALSE"
NetImpPluginINIFilePath = "NetworkPluginNone/NetworkPluginNone.ini"
NetImpParams.<size(s)> = "0 0"
FlagImpPluginINIFilePath = "NoFlagImpairPlugin/NoFlagImpairPlugin.ini"
FlagImpParams.<size(s)> = "0 0"

[AppData]
AppData.AppPluginIniFilePath = "LSEPlugin/LSEPlugin.ini"
AppData.Config = "<Cluster>\0D\0A<Name>LSEConfig</Name>\0D\0A<NumElts>6</NumElts>\0D\0A<DBL>\0D\0A<Name>NoiseVariance</Name>\0D\0A<Val>0.0001</Val>\0D\0A</DBL>\0D\0A<U32>\0D\0A<Name>IEEESystem</Name>\0D\0A<Val>13</Val>\0D\0A</U32>\0D\0A<Array>\0D\0A<Name>PMULocations</Name>\0D\0A<Dimsize>4</Dimsize>\0D\0A<U32>\0D\0A<Name>Numeric</Name>\0D\0A<Val>1</Val>\0D\0A</U32>\0D\0A<U32>\0D\0A<Name>Numeric</Name>\0D\0A<Val>2</Val>\0D\0A</U32>\0D\0A<U32>\0D\0A<Name>Numeric</Name>\0D\0A<Val>5</Val>\0D\0A</U32>\0D\0A<U32>\0D\0A<Name>Numeric</Name>\0D\0A<Val>11</Val>\0D\0A</U32>\0D\0A</Array>\0D\0A<I32>\0D\0A<Name>Vindex</Name>\0D\0A<Val>0</Val>\0D\0A</I32>\0D\0A<I32>\0D\0A<Name>Iindex</Name>\0D\0A<Val>3</Val>\0D\0A</I32>\0D\0A<String>\0D\0A<Name>DynamicRef</Name>\0D\0A<Val>..\Events\EventPlugins\Mathscript\CSVPlugin\CSV files\VoltageReferences_case13_4pmus.csv</Val>\0D\0A</String>\0D\0A</Cluster>\0D\0A"

[OutToFileConfig]
OutToFileConfig.OutputToFilePluginINIFilePath = "OutputToFileBasePlugin/OutputToFileBasePlugin.ini"
OutToFileConfig.Output File Path = "Output"
OutToFileConfig.clConfigOptions.TIME_BASE = "\00\00\00\00\00\0FB@"
OutToFileConfig.clConfigOptions.STN = "Bus_1"
OutToFileConfig.clConfigOptions.IDCODE = "0"
OutToFileConfig.clConfigOptions.rdoPolRect = "Rectangular"
OutToFileConfig.clConfigOptions.rdoFloatInt = "Float"
OutToFileConfig.clConfigOptions.PHUNIT = "\00\00\00\00\00\0FB@"
OutToFileConfig.clConfigOptions.rdoFreqDfreq = "Float"
OutToFileConfig.clConfigOptions.CHNAM.<size(s)> = "8"
OutToFileConfig.clConfigOptions.CHNAM 0 = "VA"
OutToFileConfig.clConfigOptions.CHNAM 1 = "VB"
OutToFileConfig.clConfigOptions.CHNAM 2 = "VC"
OutToFileConfig.clConfigOptions.CHNAM 3 = "V+"
OutToFileConfig.clConfigOptions.CHNAM 4 = "IA"
OutToFileConfig.clConfigOptions.CHNAM 5 = "IB"
OutToFileConfig.clConfigOptions.CHNAM 6 = "IC"
OutToFileConfig.clConfigOptions.CHNAM 7 = "I+"
OutToFileConfig.clConfigOptions.chkCfg2Prefix = "TRUE"
