[Bus1]
BusNumber = "1"
EvtPluginINIFilePath = "EventFromCSVPlugin/EventFromCSVPlugin.ini"
EvtParams.<size(s)> = "1 1"
EvtParams 0 = "GMV\Inputdata\DynamicEvent_case13_1pmus.csv"
EvtConfig.UTC Time 0 = "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00"
EvtConfig.Nominal Frequency = "60"
EvtConfig.Reporting Rate = "60"
EvtConfig.Fsamp = "960"
EvtConfig.PosSeq = "FALSE"
Start Time = "0"
End Time = "6"
PmuImpairPluginINIFilePath = "C37BehaviourPlugin/C37BehaviourPlugin.ini"
PmuImpairParams.<size(s)> = "2 1"
PmuImpairParams 0 = "8.19"
PmuImpairParams 1 = "164"
PmuImpairConfig.FilterType = "Blackman"
PmuImpairConfig.bPosSeq = "FALSE"
NetImpPluginINIFilePath = "NetworkPluginNone/NetworkPluginNone.ini"
NetImpParams.<size(s)> = "0 0"
FlagImpPluginINIFilePath = "NoFlagImpairPlugin/NoFlagImpairPlugin.ini"
FlagImpParams.<size(s)> = "0 0"

[AppData]
AppData.AppPluginIniFilePath = "ModelValidationPlugin/ModelValidationPlugin.ini"
AppData.Config = "<Cluster>\0D\0A<Name>ModelValidationConfig</Name>\0D\0A<NumElts>5</NumElts>\0D\0A<DBL>\0D\0A<Name>NoiseVariance</Name>\0D\0A<Val>1.00000000000000E-3</Val>\0D\0A</DBL>\0D\0A<I32>\0D\0A<Name>Iindex</Name>\0D\0A<Val>3</Val>\0D\0A</I32>\0D\0A<DBL>\0D\0A<Name>OffsetTime</Name>\0D\0A<Val>2.00000000000000</Val>\0D\0A</DBL>\0D\0A<I32>\0D\0A<Name>InterpolationFactor</Name>\0D\0A<Val>5</Val>\0D\0A</I32>\0D\0A<Cluster>\0D\0A<Name>Initial condition</Name>\0D\0A<NumElts>3</NumElts>\0D\0A<DBL>\0D\0A<Name>H0</Name>\0D\0A<Val>4.55000000000000</Val>\0D\0A</DBL>\0D\0A<DBL>\0D\0A<Name>xd0</Name>\0D\0A<Val>0.27500000000000</Val>\0D\0A</DBL>\0D\0A<DBL>\0D\0A<Name>D0</Name>\0D\0A<Val>4.20000000000000</Val>\0D\0A</DBL>\0D\0A</Cluster>\0D\0A</Cluster>\0D\0A"

[OutToFileConfig]
OutToFileConfig.OutputToFilePluginINIFilePath = "OutputToFileBasePlugin/OutputToFileBasePlugin.ini"
OutToFileConfig.Output File Path = "Output"
OutToFileConfig.clConfigOptions.TIME_BASE = "\00\00\00\00\00\0FB@"
OutToFileConfig.clConfigOptions.STN = "Bus_1"
OutToFileConfig.clConfigOptions.IDCODE = "0"
OutToFileConfig.clConfigOptions.rdoPolRect = "Rectangular"
OutToFileConfig.clConfigOptions.rdoFloatInt = "Float"
OutToFileConfig.clConfigOptions.PHUNIT = "\00\00\00\00\00\0FB@"
OutToFileConfig.clConfigOptions.rdoFreqDfreq = "Float"
OutToFileConfig.clConfigOptions.CHNAM.<size(s)> = "8"
OutToFileConfig.clConfigOptions.CHNAM 0 = "VA"
OutToFileConfig.clConfigOptions.CHNAM 1 = "VB"
OutToFileConfig.clConfigOptions.CHNAM 2 = "VC"
OutToFileConfig.clConfigOptions.CHNAM 3 = "V+"
OutToFileConfig.clConfigOptions.CHNAM 4 = "IA"
OutToFileConfig.clConfigOptions.CHNAM 5 = "IB"
OutToFileConfig.clConfigOptions.CHNAM 6 = "IC"
OutToFileConfig.clConfigOptions.CHNAM 7 = "I+"
OutToFileConfig.clConfigOptions.chkCfg2Prefix = "TRUE"
