function [ImpTimestamp,...
          ImpSynx,...
          ImpFreq,...
          ImpROCOF] = UserPmuImpairWrapper(PmuImpairType,...
                                       EvtTimestamp,...
                                       EvtSynx,...
                                       EvtFreq,...
                                       EvtROCOF,...
                                       ImpParams,...
                                       FilterType,...
                                       F0)
%This function acts as a wrapper for all of the user-defined
%PMU impairment plugins.

%To add a plugin:
% 1. Create a function containing your impairment.
% 2. Call the function from this UserPmuWrapper by adding a 
%    case to the switch-case statement.
%    Note: You may choose to extract parameters and configurations
%          in the switch-case statement. However, it is not advised
%          because it may lead to a very confusing wrapper file
%          as more and more user impairments are added.
% 3. Create a .ini file containing the path to UserPmuPlugins.lvclass
%    and the PMU Impairment type (PmuImpairType)

switch PmuImpairType
    case 'UserPmuImpair1'
        [ImpTimestamp,...
          ImpSynx,...
          ImpFreq,...
          ImpROCOF] = UserPmuImpair1(EvtTimestamp,...
                                       EvtSynx,...
                                       EvtFreq,...
                                       EvtROCOF,...
                                       ImpParams,...
                                       FilterType,...
                                       F0);
end
end