function [ImpTimestamp,...
          ImpSynx,...
          ImpFreq,...
          ImpROCOF] = UserPmuImpair1(EvtTimestamp,...
                                       EvtSynx,...
                                       EvtFreq,...
                                       EvtROCOF,...
                                       ImpParams,...
                                       FilterType,...
                                       F0);
%Your impairment goes in here.

ImpTimestamp = EvtTimestamp;
ImpSynx = EvtSynx;
ImpFreq = EvtFreq;
ImpROCOF = EvtROCOF;

end

