function [NetworkTime,PktLoss] = NetworkImpairWrapper(...
                                    Time,...
                                    Params)
timevector = Time;
service_mean = Params(1,1);
service_deviation = Params(2,1);
p_up = Params(3,1);
q_down = Params(4,1);
queuethreshold = Params(5,1);
lambda=60;
% PMUID=1;
[NetworkTime, PktLoss] = networkimpairement(timevector,...
                                          lambda,...
                                          service_mean,...
                                          service_deviation,...
                                          p_up,...
                                          q_down,...
                                          queuethreshold);